os: linux
dist: xenial
language: go
go:
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - master
go_import_path: github.com/chronomq/chronomq
cache:
  directories:
    - "$HOME/gopath/pkg/mod"

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

before_script:
  - export GO111MODULE=off
  - >
    mkdir $HOME/protocdl &&
    cd $HOME/protocdl &&
    wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip &&
    unzip protoc-3.11.4-linux-x86_64.zip -d protoc &&
    chmod 755 -R protoc &&
    BASE=/usr &&
    sudo rm -rf $BASE/include/google/protobuf/ &&
    sudo cp protoc/bin/protoc $BASE/bin &&
    sudo cp -R protoc/include/* $BASE/include
  - cd $TRAVIS_BUILD_DIR
  - go generate ./...
  - go mod tidy
  - go mod vendor

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled

env:
  global:
    GOARCH=amd64
    GO111MODULE=off
