os: linux
dist: xenial
language: go
go:
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - master
go_import_path: github.com/chronomq/chronomq
cache:
  directories:
    - "$HOME/gopath/pkg/mod"

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

before_script:
  - sudo apt update && sudo apt install protobuf-compiler -y
  - go generate ./...
  - GO111MODULE=on go mod tidy
  - GO111MODULE=on go mod vendor

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled

env:
  global:
    GOARCH=amd64
