language: go
go:
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - master
before_install:
  - go get -v golang.org/x/lint/golint
script:
  - golint pkg/... cmd/...
  - go test ./...
install: true
env:
  global:
    - GO111MODULE=on
